@startuml THUBOT

left to right direction

actor Student as s
actor ProspectiveStudent as ps

package GeneralInformation {
  usecase "UC1" as UC1
  usecase "UC2" as UC2
  usecase "UC3" as UC3
}

package AnotherInformation {
    usecase "UC4" as UC4
}

s --> UC1
s --> UC2

ps --> UC3
ps --> UC4

@enduml